DOMAIN=ejemplo.com
DOMAIN_WWW=www.ejemplo.com
ADMIN_EMAIL=admin@ejemplo.com
BACKEND_PORT=3000
APP_PROFILE=carthtml
BACKEND_APP_DIR=/var/www/carthtml
BACKEND_SERVICE=carthtml
SQLITE_DB_PATH=/var/www/carthtml/data/store.sqlite
GIT_REPO_URL=https://github.com/MartinAlejandroOviedo/carthtml.git
GIT_BRANCH=main
SOURCE_REPO_PATH=/home/martin/Documentos/GitHub/carthtml
FTP_USER=ftpapp
FTP_DIR=/var/www/ftp
FTP_PASV_MIN=30000
FTP_PASV_MAX=30100
